### ISSUE TITLE
2018920012 김영석 창의공학기초설계 게임 시스템 정리

### ISSUE THREAD

**Issue by rpfps3232** [gyuZzang/GGyu#1]
# 시스템
   * 시작화면
     * 게임시작 버튼
     * 옵션 창
   * 게임 내
     * 클릭 하는 요소 (서로 다른창에 존재함)
       * 공부 (처음엔 20씩 상승)
         * 학점이 증가할 수록 많이 증가
       * 알바 (처음엔 100원씩 상승)
         * 학점이 증가할 수록 더 많은 돈을 벌 수 있음 ex) 편의점 알바 > 과외 
     * 업적 및 퀘스트
       * ~공부량을 달성하라
       * ~원을 벌어라
       * ~학점을 얻어라 등등
     * 아이템(돈으로 구매 가능)
       * 전공책
       * 볼펜
       * 공책
     * 보스 (시험)
       * 학점별로 나누어짐 (1학점, 2학점...)
       * 공부량에 따라 가하는 데미지 증가
       * 쓰러트릴 경우 학점을 얻음
     * 졸업
       * 일정학점을 넘길 경우 가능
       * 졸업 시 모든 돈, 아이템, 공부량, 학점이 초기화 됨
       * 졸업 시 보유하고 있던 학점에 따라 특성포인트 얻음
     * 특성
       * 공부량 (0+5%) 상승
       * 알바로 버는 돈 (0+10%) 상승
       * 공부량 : 보스에게 입히는 데미지 계수 증가
       * ~초 마다 자동으로 클릭

**Comment by rpfps3232** [comment]
# 해야할 일
  * 아이템 이름, 능력, 가격 등 다양하게 정하기
  * 게임 내에서 보여질 수치들 적당히 조정하기(다른 게임들 참고)
  * 보스전에 대한 수치 설정 및 진행 방식 정하기
  * 업적 및 퀘스트 다양화

**Comment by gyuZzang** [comment]
게임 내 보여지는 수치관련해서 결정할 요소들이 엄청 많으니까 따로 이슈 만드는게 좋을 듯!?
